<?php
/**
 * Copyright © 28Software (https://28software.com)
 * See LICENSE for the license details.
 */
declare(strict_types = 1);

use Magento\Framework\View\Element\Template;
use TESoftware\BingConversionTracking\ViewModel\CheckoutTracker;

/** @var Template $block */
/** @var CheckoutTracker $viewModel */
$viewModel = $block->getViewModel();
?>
<?php if ($viewModel->isActive()) : ?>
<script>
    <!-- BEGIN: Bing Conversion Tracking -->
    window.uetq = window.uetq || [];
    window.uetq.push({
        'ec': 'Ecommerce',
        'ea': 'Purchase',
        'el': 'Successful Sale',
        'ev': '0',
        'gv': <?= /** @noEscape */ $viewModel->getOrderSubtotalJson($block->getOrderId()) ?>
    });
    <!-- END: Bing Conversion Tracking -->
</script>
<?php endif; ?>
